version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
    restart: always
    depends_on:
      - db

  db:
    image: chromadb/chromadb:latest
    container_name: chromadb
    volumes:
      - chromadb_data:/data
    ports:
      - "8001:8001"

volumes:
  chromadb_data:
